- name: varibales from task playbook
  hosts: web01
  become: yes
  vars:
    COURSE: "Devops"
    DURATION: "110 hours"
    NAME: "Sivakumar"
  tasks:
    - name: task -1 of the playbook
      vars:
        COURSE: "DEVOPS with AWS"
      ansible.builtin.debug:
        msg: "Hi All, I am learning {{COURSE}} from {{NAME}} for duration {{DURATION}}"
