- name: playbook to capture the variable values from prompt
  hosts: web01
  become: yes
  vars_prompt:
    - name: USERNAME
      prompt: Please enter your name
      private: false
    - name: PASSWORD
      prompt: Please enter your password
      private: true
  tasks:
    - name: task-1
      ansible.builtin.debug:
        msg: "My Username: {{USERNAME}} and password: {{PASSWORD}}"
