- name: playbook for key value loop
  hosts: web01
  become: yes
  tasks:
    - name: loop
      ansible.builtin.package:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
        - { name: "nginx", state: "present" }
        - { name: "git", state: "present" }
        - { name: "mysql", state: "present" }
        - { name: "postfix", state: "present" }
