- hosts: localhost
  gather_facts: True
  become: yes
  vars:
    AMI_ID: ami-03265a0778a880afb
    SECURITY_GP: sg-0170a2c37d33656c2
    INSTANCE_TYPE: t2.micro
    REGION: us-east-1
    ZONE: roboshopapp.website
  tasks:
    - name: start an instance
      amazon.aws.ec2_instance:
        name: "{{item}}"
        instance_type: "{{ 't3.medium' if item in ['mongodb', 'mysql', 'shipping'] else INSTANCE_TYPE }}"
        security_group: "{{SECURITY_GP}}"
        image_id: "{{AMI_ID}}"
        tags:
          Environment: "{{item}}"
        exact_count: 1
        region: "{{REGION}}"
    - name: Adding the records in Rout53
      amazon.aws.route53:
        state: present
        zone: "{{ZONE}}"
        record: "{{item}}.{{ZONE}}"
        type: A
        ttl: 7200
        value: 1.1.1.1,2.2.2.2,3.3.3.3
        wait: true
      loop:
        - mongodb
        - catalogue
        - redis
        - user
        - cart
        - mysql
        - shipping
        - rabbitmq
        - payment
        - dispatch
        - web
