- hosts: localhost
  gather_facts: True
  become: yes
  vars:
    AMI_ID: ami-03265a0778a880afb
    SECURITY_GP: sg-0170a2c37d33656c2
    INSTANCE_TYPE: t2.micro
    REGION: us-east-1
    ZONE: roboshopapp.website
  tasks:
    - name: start an instance
      amazon.aws.ec2_instance:
        name: "{{item}}"
        instance_type: "{{ 't3.medium' if item in ['mongodb', 'mysql', 'shipping'] else INSTANCE_TYPE }}"
        security_group: "{{SECURITY_GP}}"
        image_id: "{{AMI_ID}}"
        tags:
          Environment: "{{item}}"
        exact_count: 1
        region: "{{REGION}}"
      loop:
        - mongodb
        - catalogue
        - redis
        - user
        - cart
        - mysql
        - shipping
        - rabbitmq
        - payment
        - dispatch
        - web
    - name: display Ip addess
      ansible.builtin.debug:
        vars: ansible_distribution
