- hosts: localhost
  gather_facts: False
  become: yes
  vars:
    AMI_ID: ami-03265a0778a880afb
    SECURITY_GP: sg-0170a2c37d33656c2
    INSTANCE_TYPE: ""
    REGION: us-east-1
  tasks:
    - name: start an instance
      amazon.aws.ec2_instance:
        name: "{{item}}"
        instance_type: "{{INSTANCE_TYPE}}"
        security_group: "{{SECURITY_GP}}"
        image_id: "{{AMI_ID}}"
        tags:
          Environment: "{{item}}"
        exact_count: 1
        region: us-east-1
      loop:
        - mongodb
        - redis
        - catalogue
        - web
