- hosts: localhost
  gather_facts: True
  become: yes
  vars:
    AMI_ID: ami-03265a0778a880afb
    SECURITY_GP: sg-0170a2c37d33656c2
    INSTANCE_TYPE: t2.micro
    REGION: us-east-1
    ZONE: roboshopapp.website
  tasks:
    - name: Start instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: "{{ 't3.medium' if item in ['mongodb', 'mysql', 'shipping'] else INSTANCE_TYPE }}"
        security_group: "{{ SECURITY_GP }}"
        image_id: "{{ AMI_ID }}"
        tags:
          Environment: "{{ item }}"
        exact_count: 1
        region: "{{ REGION }}"
        wait: true
      loop:
        - mongodb
        - redis
      register: ec2_instances

    - name: Access private_ip_address for 'mongodb' and 'redis' instances
      debug:
        msg: "Private IP Address of '{{ item.item }}' instance is {{ item.instances[0].private_ip_address }}"
      loop: "{{ ec2_instances.results }}"
      loop_control:
        label: "{{ item.item }}"
      when:
        - item.item in ['mongodb', 'redis']

    # - name: Wait for instances to reach 'running' state
    #   wait_for:
    #     host: "{{ item.instance.public_ip_addresses }}"
    #     port: 22 # Replace with the appropriate port
    #     state: started
    #     delay: 10
    #     timeout: 600 # Adjust the timeout value as per your requirements
    #   loop: "{{ ec2_instances.results }}"
    #   when: item.instance.public_ip_addresses is defined

    # - name: Create Route 53 DNS record
    #   route53:
    #     command: create
    #     zone: "{{ ZONE }}" # Replace with your Route 53 zone ID or name
    #     record: "{{ item.item + '.' + ZONE }}"
    #     type: A
    #     ttl: 300 # Adjust TTL as per your requirement
    #     value: "{{ item.instance.private_ip_address }}" # Use 'private_ip' for private IP
    #   loop: "{{ ec2_instances.results }}"
    #   when: item.instance.public_ip_addresses is defined
