- hosts: localhost
  gather_facts: True
  become: yes
  vars:
    AMI_ID: ami-03265a0778a880afb
    SECURITY_GP: sg-0170a2c37d33656c2
    INSTANCE_TYPE: t2.micro
    REGION: us-east-1
    ZONE: roboshopapp.website
  tasks:
    - name: Start an instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: "{{ 't3.medium' if item in ['mongodb', 'mysql', 'shipping'] else INSTANCE_TYPE }}"
        security_group: "{{ SECURITY_GP }}"
        image_id: "{{ AMI_ID }}"
        tags:
          Environment: "{{ item }}"
        exact_count: 1
        region: "{{ REGION }}"
      loop:
        - mongodb
        - catalogue
        - redis
        - user
        - cart
        - mysql
        - shipping
        - rabbitmq
        - payment
        - dispatch
        - web
      register: ec2_instances

    - name: Create Route 53 DNS record
      route53:
        command: create
        zone: "{{ ZONE }}" # Replace with your Route 53 zone ID or name
        record: "{{ item.item + '.' + ZONE }}"
        type: A
        ttl: 300 # Adjust TTL as per your requirement
        value: "{{ item.instance.private_ip }}" # Use 'private_ip' for private IP
      loop: "{{ ec2_instances.results }}"
      when: item.instance.private_ip is defined
