- name: play-1
  hosts: web01
  become: yes
  tasks:
    - name: play-1 task-1
      ansible.builtin.debug:
        msg: "Hello i am printing from pplaybook 1 and task 1"

- name: play-2
  hosts: web01
  become: yes
  tasks:
    - name: play-2 task-1
      ansible.builtin.debug:
        msg: "Hello I am printing from play-2 and task-1"
