- name: redis
  hosts: redis
  become: yes
  tasks:
    - name: Install redis rpm from repo
      ansible.builtin.shell: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y; dnf module enable redis:remi-6.2 -y; dnf install redis -y;

    - name: allow remote conncections
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: "127.0.0.1"
        replace: "0.0.0.0"

    - name: start and enable redis
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes
