- name: redis
  hosts: redis
  become: yes
  tasks:
    - name: Install redis rpm from repo
      ansible.builtin.shell: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y; dnf module enable redis:remi-6.2 -y; dnf install redis -y;
